# **Part 1: Data Exploration with Pandas**

**Load the Dataset**

In [ ]:
import pandas as pd
data = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [ ]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
data.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

**Data Summary**

In [ ]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
unique = data.total_bedrooms.unique()
unique

array([1283., 1901.,  174., ..., 1637., 1308.,  936.])

In [ ]:
print(f"There are {unique.shape[0]} unique values for total_bedrooms column in given dataset")

There are 1848 unique values for total_bedrooms column in given dataset


**Data Transformation**

In [ ]:
data['total_bedrooms_per_total_rooms'] = data['total_bedrooms'] / data['total_rooms']
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  \
0          1015.0       472.0         1.4936             66900.0   
1          1129.0       463.0         1.8200             80100.0   
2           333.0       117.0         1.6509             85700.0   
3           515.0       226.0         3.1917             73400.0   
4           624.0       262.0         1.9250             65500.0   
...           ...         ...            ...                 ...   
16995       907.0       369.0         2.3571            111400.0   
16996      1194.0       465.0         2.5179             79000.0   
16997      1244.0       456.0         3.0313            103600.0   
16998      1298.0       478.0         1.9797             85800.0   
16999       806.0       270.0         3.0147             94600.0   

       total_bedrooms_per_total_rooms  
0                            0.228617  
1                            0.248497  
2                            0.241667  
3                            0.224517  
4                            0.224209  
...                               ...  
16995                        0.177718  
16996                        0.224777  
16997                        0.198356  
16998                        0.206587  
16999                        0.164835  

[17000 rows x 10 columns]

In [ ]:
data.total_bedrooms_per_total_rooms.mean()

0.21275998821034803

In [ ]:
data.total_bedrooms_per_total_rooms.std()

0.057823008903161756

**Data Filtering**

In [ ]:
filter = data[data['median_income']>5]
filter

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [ ]:
subset = filter[(filter['total_rooms']>10000) & (filter['median_house_value']<150000)]
subset

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
9248    -119.08     35.32                 8.0      11609.0          2141.0   

      population  households  median_income  median_house_value  \
9248      5696.0      2100.0         5.0012            106300.0   

      total_bedrooms_per_total_rooms  
9248                        0.184426

**Export Modified Data**

In [ ]:
data.to_csv('Modified_Data.csv', index=False)

This part was intended for use of pandas library for droping, filtering, exporting data. It also included basic functions such as head, tail, describe and mathemical terms like mean, min, max etc. It also dealt with the attribute shape.

# **Part 2: Numerical Analysis with NumPy**

In [ ]:
import numpy as np

**Array Creation and Indexing**

In [ ]:
array = np.arange(1,21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
array[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
array1 = np.random.randint(11, 100, (5,4)) # Considering both 10, 100 are excluded
array1

array([[56, 30, 67, 65],
       [34, 67, 34, 53],
       [31, 32, 64, 15],
       [83, 92, 34, 50],
       [40, 67, 52, 69]])

In [ ]:
array1[:3,:2]

array([[56, 30],
       [34, 67],
       [31, 32]])

**Array Manipulation**

In [ ]:
array.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
array1.flatten()

array([56, 30, 67, 65, 34, 67, 34, 53, 31, 32, 64, 15, 83, 92, 34, 50, 40,
       67, 52, 69])

In [ ]:
array2 = np.random.randint(5, 60, (4,6))
array2
# Taking secong array randomly for matrix multiplication by keeping the mathematical rules for it in consideration.

array([[25,  8, 34,  7, 46, 11],
       [52, 48, 41, 51, 29, 53],
       [ 6, 44,  7,  9, 27, 47],
       [37, 49, 22, 47, 32, 20]])

In [ ]:
np.dot(array1,array2)

array([[5767, 8021, 5033, 5580, 7335, 6655],
       [6499, 7581, 5307, 6452, 6121, 6583],
       [3378, 5335, 3144, 3130, 4562, 5345],
       [8913, 9026, 7932, 7929, 9004, 8387],
       [7349, 9205, 5989, 7408, 7395, 7815]])

**Boolean and Fancy Indexing**

In [ ]:
array2 = np.random.randint(1,100, (1,50)) # Again excluding 0, 100 as it is given between in question
array2 = array2.flatten()
array2

array([91,  4,  1, 38, 86, 57, 57, 36, 18, 52, 96, 84, 13, 64, 22, 94,  8,
       43, 59, 65, 13, 54,  3, 99, 15, 76,  1, 50, 96, 85, 53, 40,  6, 21,
       37, 16, 23, 39, 10, 51, 24, 45, 71, 70, 43, 85, 39, 21, 87, 47])

In [ ]:
array2[array2 > 50]

array([91, 86, 57, 57, 52, 96, 84, 64, 94, 59, 65, 54, 99, 76, 96, 85, 53,
       51, 71, 70, 85, 87])

In [ ]:
array2[3:24:2] # Here we use fancy indexing to get alternate elements starting from 3rd index to 23rd index.

array([38, 57, 36, 52, 84, 64, 94, 43, 65, 54, 99])

**Statistical Operations**

In [ ]:
array1

array([[56, 30, 67, 65],
       [34, 67, 34, 53],
       [31, 32, 64, 15],
       [83, 92, 34, 50],
       [40, 67, 52, 69]])

In [ ]:
array1.mean(axis=0)

array([48.8, 57.6, 50.2, 50.4])

In [ ]:
array1.max(axis=0)

array([83, 92, 67, 69])

In [ ]:
array1.sum(axis=0)

array([244, 288, 251, 252])

In [ ]:
mask = array1 > array1.mean(axis=0)

In [ ]:
array1[mask]

array([56, 67, 65, 67, 53, 64, 83, 92, 67, 52, 69])

Part 2 of this assignment was there for use of the library NumPy. It dealt with arrays, matrix using reshape, indexing and mathematical operation like product of matrices and many more. We also revised the way to create matrix and array with random numbers whether integer or float.

# **Part 3: Problem Solving with Python Basics**

**Loops and Conditional Statements**

In [ ]:
series = [0,1]
for  i in series:
  if i < 100:
    a = series[-1]+series[-2]
    if a > 100:
      break
    series.append(a)
print(series)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [ ]:
for i in range(1,51):
  if (i%3 == 0) and (i%5 == 0):
    print("FizzBuzz")
  elif i%3==0:
    print("Fizz")
  elif i%5==0:
    print("Buzz")
  else:
    print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


**Variable-Length Arguments**

In [ ]:
for i in range(2):
  lis = input("Enter the list of numbers: ")
  import ast
  c = ast.literal_eval(lis)
  c.sort()
  terms = len(c)
  if terms%2 != 0 :
    y =int((terms-1)/2)
    print(f"Median of the numbers is {c[y]}")
  else:
    a = int((terms+1)/2)
    b = int((terms-1)/2)
    x = (c[a]+c[b])/2
    print(f"Median of the numbers is {x}")

Enter the list of numbers: [18,15,21]
Median of the numbers is 18
Enter the list of numbers: [16,25,31,8]
Median of the numbers is 20.5


In [ ]:
a = input("Enter the numbers: ")
import ast
list = ast.literal_eval(a)
avg = sum(list)/len(list)
print(avg)

Enter the numbers: 1,4,5,6,7,9
5.333333333333333


**Error Handling**

In [ ]:
try:
  a = int(input("Enter dividend: "))
  b = int(input("Enter divisor: "))
  print(a/b)
except ZeroDivisionError as e:
  print(e)

Enter dividend: 5
Enter divisor: 0
division by zero


This part was based on basic python programming more specifically for functins, loops etc. This also included a problem that used try.. except to eliminate the error as per the need.

# **Part 4: Bonus Challenge**

**Advanced NumPy Manipulation**

In [ ]:
array3 = np.random.rand(3,4,2)
array3

array([[[0.43490065, 0.351898  ],
        [0.10617427, 0.41468392],
        [0.49606639, 0.4253964 ],
        [0.79555185, 0.21261738]],

       [[0.78167476, 0.33792788],
        [0.87898618, 0.10320926],
        [0.32275203, 0.5287922 ],
        [0.97409852, 0.30255389]],

       [[0.92549691, 0.5697558 ],
        [0.72464004, 0.60890463],
        [0.01821287, 0.64882014],
        [0.22739819, 0.4060696 ]]])

In [ ]:
array3.swapaxes(0,1)

array([[[0.43490065, 0.351898  ],
        [0.78167476, 0.33792788],
        [0.92549691, 0.5697558 ]],

       [[0.10617427, 0.41468392],
        [0.87898618, 0.10320926],
        [0.72464004, 0.60890463]],

       [[0.49606639, 0.4253964 ],
        [0.32275203, 0.5287922 ],
        [0.01821287, 0.64882014]],

       [[0.79555185, 0.21261738],
        [0.97409852, 0.30255389],
        [0.22739819, 0.4060696 ]]])

In [ ]:
array3.sum(axis=0)

array([[2.14207231, 1.25958168],
       [1.70980049, 1.12679781],
       [0.83703129, 1.60300874],
       [1.99704856, 0.92124087]])

In [ ]:
array4 = np.random.rand(3,4)
array4

array([[0.73166628, 0.48009974, 0.99558289, 0.57053405],
       [0.18147731, 0.99155412, 0.51547949, 0.25466694],
       [0.84114378, 0.66026399, 0.36701845, 0.4185672 ]])

In [ ]:
vector = np.random.rand(1,4)
vec = vector.flatten()
vec

array([0.2945247 , 0.77406327, 0.24973753, 0.31519067])

In [ ]:
array4 + vec

array([[1.02619098, 1.25416301, 1.24532041, 0.88572472],
       [0.47600201, 1.76561739, 0.76521701, 0.56985761],
       [1.13566847, 1.43432726, 0.61675597, 0.73375787]])

This was more focussed on NumPy. It included making 3D array, swapping axis and most importantly operating on desired axis.